# Generated by Django 3.2.4 on 2021-06-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('function', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('amonds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('amonds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('communications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Amonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_fk', to='JournauxDeCaissePbrussels.employee')),
                ('payement_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payement_fk', to='JournauxDeCaissePbrussels.payment')),
                ('recipe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_fk', to='JournauxDeCaissePbrussels.recipe')),
            ],
        ),
    ]
